from workbench.utils.prompts.prompts import (
    NETWORK_AGENT_PROMPT,
    RESEARCH_PROMPT,
    SUPERVISOR_AGENT_PROMPT,
    SYSTEM_AGENT_PROMPT,
)

__all__ = [
    "RESEARCH_PROMPT",
    "SYSTEM_AGENT_PROMPT",
    "NETWORK_AGENT_PROMPT",
    "SUPERVISOR_AGENT_PROMPT",
]
