from workbench.utils.prompts.prompts import (
    FILE_AGENT_PROMPT,
    NETWORK_AGENT_PROMPT,
    RESEARCH_AGENT_PROMPT,
    SUPERVISOR_AGENT_PROMPT,
    SYSTEM_AGENT_PROMPT,
)

__all__ = [
    "RESEARCH_AGENT_PROMPT",
    "SYSTEM_AGENT_PROMPT",
    "NETWORK_AGENT_PROMPT",
    "SUPERVISOR_AGENT_PROMPT",
    "FILE_AGENT_PROMPT",
]
